# Generated by Django 6.0.5 on 2026-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfeature',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_btn_text_az',
            field=models.CharField(default='bizimlə əməkdaşlıq et', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_btn_text_en',
            field=models.CharField(default='bizimlə əməkdaşlıq et', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_btn_text_ru',
            field=models.CharField(default='bizimlə əməkdaşlıq et', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_btn_text_az',
            field=models.CharField(default='xidmətlərə bax', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_btn_text_en',
            field=models.CharField(default='xidmətlərə bax', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_btn_text_ru',
            field=models.CharField(default='xidmətlərə bax', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='subtitle_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='subtitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='subtitle_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whowehelp',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whowehelpitem',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whowehelpitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whowehelpitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
