# Generated by Django 6.0.5 on 2026-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_aboutfeature_description_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='Maksimum 70 simvol', max_length=70)),
                ('meta_title_az', models.CharField(help_text='Maksimum 70 simvol', max_length=70, null=True)),
                ('meta_title_en', models.CharField(help_text='Maksimum 70 simvol', max_length=70, null=True)),
                ('meta_title_ru', models.CharField(help_text='Maksimum 70 simvol', max_length=70, null=True)),
                ('meta_description', models.TextField(help_text='Maksimum 160 simvol', max_length=160)),
                ('meta_description_az', models.TextField(help_text='Maksimum 160 simvol', max_length=160, null=True)),
                ('meta_description_en', models.TextField(help_text='Maksimum 160 simvol', max_length=160, null=True)),
                ('meta_description_ru', models.TextField(help_text='Maksimum 160 simvol', max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Vergüllə ayrılmış açar sözlər', max_length=255)),
                ('meta_keywords_az', models.CharField(blank=True, help_text='Vergüllə ayrılmış açar sözlər', max_length=255, null=True)),
                ('meta_keywords_en', models.CharField(blank=True, help_text='Vergüllə ayrılmış açar sözlər', max_length=255, null=True)),
                ('meta_keywords_ru', models.CharField(blank=True, help_text='Vergüllə ayrılmış açar sözlər', max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_title_az', models.CharField(blank=True, max_length=70, null=True)),
                ('og_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('og_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_description_az', models.TextField(blank=True, max_length=200, null=True)),
                ('og_description_en', models.TextField(blank=True, max_length=200, null=True)),
                ('og_description_ru', models.TextField(blank=True, max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 px tövsiyə olunur', null=True, upload_to='seo/')),
                ('twitter_title', models.CharField(blank=True, max_length=70)),
                ('twitter_title_az', models.CharField(blank=True, max_length=70, null=True)),
                ('twitter_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('twitter_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('twitter_description', models.TextField(blank=True, max_length=200)),
                ('twitter_description_az', models.TextField(blank=True, max_length=200, null=True)),
                ('twitter_description_en', models.TextField(blank=True, max_length=200, null=True)),
                ('twitter_description_ru', models.TextField(blank=True, max_length=200, null=True)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=20)),
                ('canonical_url', models.URLField(blank=True, help_text='Məs: https://finnab.az')),
                ('robots', models.CharField(default='index, follow', max_length=50)),
                ('schema_organization_name', models.CharField(blank=True, max_length=100)),
                ('schema_phone', models.CharField(blank=True, max_length=50)),
                ('schema_email', models.EmailField(blank=True, max_length=254)),
                ('schema_address', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Ayarları',
                'verbose_name_plural': 'SEO Ayarları',
            },
        ),
    ]
