# Generated by Django 6.0.5 on 2026-06-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_seosettings'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': 'SEO Ayarı', 'verbose_name_plural': 'SEO Ayarları'},
        ),
        migrations.AddField(
            model_name='seosettings',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Signal tərəfindən avtomatik yaradılıb'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='page_identifier',
            field=models.CharField(blank=True, help_text='Ümumi sayt SEO-su üçün: "global" yazın', max_length=50),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Maksimum 160 simvol', max_length=160),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description_az',
            field=models.TextField(blank=True, help_text='Maksimum 160 simvol', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Maksimum 160 simvol', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Maksimum 160 simvol', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Maksimum 70 simvol', max_length=70),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title_az',
            field=models.CharField(blank=True, help_text='Maksimum 70 simvol', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Maksimum 70 simvol', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Maksimum 70 simvol', max_length=70, null=True),
        ),
    ]
